name = "bilibili-tg-live"
main = "_worker.js"
compatibility_date = "2026-07-19"
compatibility_flags = ["nodejs_compat"]

routes = [
  "live.262832.xyz/*"
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "ROOM_STORE"
id = "20f76ff92a9749df88fca03981bb02a2"

[triggers]
crons = ["* * * * *"]

[vars]
ADMIN_USER = "admin"
ADMIN_PASSWORD = "Ow114514"
