name = "bilibili-tg-live"
main = "_worker.js"
compatibility_date = "2026-07-19"
compatibility_flags = ["nodejs_compat"]

workers_dev = true
preview_urls = true

routes = [
  { pattern = "live.262832.xyz/*", zone_id = "2115bcaa342e799af5b0c9b5fe3395aa" },
  "bilibili-tg-live.ctn32.workers.dev/*",
  "*.bilibili-tg-live.ctn32.workers.dev/*"
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
persist = true
head_sampling_rate = 1

[[kv_namespaces]]
binding = "ROOM_STORE"
id = "20f76ff92a9749df88fca03981bb02a2"

[triggers]
crons = ["* * * * *"]

[vars]
ADMIN_USER = "admin"
ADMIN_PASSWORD = "Ow114514"
