name = "bilibili-live-backend"
main = "_worker.js"
compatibility_date = "2026-07-19"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "live-tg"
database_id = "9aa5865e-1b19-49cc-8915-95729484a82d"   # 替换为实际 D1 ID

[triggers]
crons = ["* * * * *"]

[vars]
ADMIN_USER = "admin"
ADMIN_PASSWORD = "Ow114514"
FRONTEND_URL = "https://live.262832.xyz"
